// Re-export types generated by: npx supabase gen types typescript --project-id kljtmxctbhzicedyeqgw
// To regenerate: npx supabase gen types typescript --project-id kljtmxctbhzicedyeqgw > lib/supabase/database.types.ts
export type { Database, Json } from "./database.types"
